# site properties and page defaults
title: Dinglab
subtitle: Physics Department, Tsinghua University
description: 
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: dingshq@mail.tsinghua.edu.cn
  orcid: false
  google-scholar: https://scholar.google.com/citations?user=3yYcICQAAAAJ&hl=zh-CN&oi=ao
  github: false
  twitter: false
  youtube: false

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
